[agent]
  interval = "10s"
  flush_interval = "10s"
  round_interval = true

###############################################################################
# INPUT: MQTT (from local Mosquitto broker)
###############################################################################
[[inputs.mqtt_consumer]]
  servers = ["tcp://edgex-mqtt-broker:1883"] # from Docker containers
  topics = ["sensor"] # where to subscribe 
  qos = 0
  client_id = "telegraf-sensor-subscriber" # how we appear
  username = ""   # Optional
  password = ""   # Optional
  data_format = "json"
  json_time_key = "time"          # Optional: match your field names
  json_time_format = "unix"            # or "2006-01-02T15:04:05Z07:00"
  tag_keys = ["ID"]

###############################################################################
# OUTPUT: Remote InfluxDB (1.x)
###############################################################################
[[outputs.influxdb]]
  urls = ["http://<IP>:<PORT>"] # REPLACE WITH CLOUD INFLUXDB IP & PORT
  database = "sensordata"
  username = "<username>"
  password = "<password>"
  timeout = "5s"

